from openai import OpenAI

client = OpenAI()

prompt = """I will provide you a date and a piece of excerpt from a news transcript. Please classify the excerpt. There are four types of excerpts:

• ELECTION: 
    An excerpt is considered an election story if it: 
        Mentions an upcoming election, 
        Mentions a candidate involved in an upcoming election by name 
        Focuses on the current duties or actions of an incumbent who is running for re-election or different office — or on issues in the campaign, by explicitly noting that they are election issues.
• NON-ELECTION: An excerpt is considered a non-election story if it contains a story that is irrelavant to the upcoming election and does not mention the candidates involvedin the election.
• BOTH: An excerpt is considered both if it both contains an election story and a non-election story.
• NEITHER: An excerpt is considered neither if it does not contain an election story or a non-election story.

TIME: SEP 5 2008 

EXCERPT: """

story = """OVERNIGHT FLAMES LIGHT UP THE SKY IN CALIFORNIA WHERE A MASSIVE WILDFIRE IS NOWHERE CLOSE TO BEING UNDER CONTROL. MORE RESIDENTS FORCED TO PACK UP AND LEAVE THEIR HOMES BEHIND. THOUSANDS OF FIREFIGHTERS ARE BATTLING THOSE FLAMES AND HOT, DRY WEATHER ISN'T MAKING THE FIGHT ANY EASIER. FOX'S ADAM HOUSELY HAS MORE ON THE BLAZE AND JUST HOW CLOSE IT'S COMING TO A NATIONAL TREASURE. FIRE CREWS IN CALIFORNIA ARE STILL TRYING TO TAME A WILDFIRE BURNING JUST OUTSIDE OF YOSEMITE NATIONAL PARK. THE BLAZE HAS BURNED MORE THAN 26,000 ACRES. THAT'S OVER 46 SQUARE MILES. AND CONTINUES TO INCH CLOSER AND CLOSER TO THE NATIONAL PARK. HIGHWAY 140, THE MAIN ROAD LEADING TO AND FROM THE ENTRANCE TO YOSEMITE, HAS BEEN SHUT DOWN AT TIMES BECAUSE OF THE SMOKE. MORE THAN 2 DOZEN HOMES HAVE BURNED SINCE THE FIRE WAS SPARKED LAST FRIDAY, AND ABOUT 300 OTHERS ARE STILL THREATENED. PEOPLE ARE PACKING UP WHAT THEY CAN BEFORE THEY HIT THE ROAD. MANY ARE HAVING A HARD TIME LEAVING THEIR LIFE BEHIND. THIS IS MY COMMUNITY. I GREW UP HERE MY WHOLE LIFE. AND JUST TO LOSE IT IS HEART-BREAKING. SOME FOLKS DIDN'T GET A CHANCE TO SAVE ANYTHING FROM THEIR HOMES BEFORE THE FLAMES CAME AND REDUCED EVERYTHING TO A PILE OF ASH. ALL MY BANK PAPERS AND ALL MY RECORDS AND EVERYTHING ARE BURNED UP. I'VE GOT ABSOLUTE HI NOTHING. OTHERS ARE USING THIS EXPERIENCE TO LEARN FOR THE NEXT TIME A FIRE MIGHT COME TO THIS AREA. I LEARNED IF IT EVER HAPPENS AGAIN I'M GOING TO HAVE A BOX, SOMETHING READY THAT WE CAN PULL OUT OF THERE. THOUSANDS OF FIREFIGHTERS ARE HERE FIGHTING THIS FIRE, BUT RUGGED TERRAIN, TEMPERATURES CREEPING TOWARDS TRIPLE DIGITS AND ALSO LOW HUMIDITY ALONG WITH PLENTY OF FUEL FOR THE FIRE IS MAKING THIS BLAZE A VERY TOUGH BATTLE. MORE FIRE CREWS ARE COMING FROM ACROSS THE STATE AND ALSO OTHER WESTERN STATES TO HELP BATTLE THIS FIRE. THE LATEST IN CALIFORNIA SO FAR THIS FIRE SEASON, NEARLY 2100 FIRES HAVE BURNED HERE, MORE THAN 1 MILLION-ACRES HAVE GONE UP. IN MARIPOSA, CALIFORNIA, ADAM HOUSELY, FOX NEWS. YOSEMITE NATIONAL PARK REMAINS OPEN DURING THE FIRES BUT SOME TOURISTS ARE STAYING AWAY. ONE FAMILY STARTED CAMPING ON SUNDAY AND DECIDED TO LEAVE THE VERY NEXT MORNING AFTER ASH BEGAN FALLING ON THEIR TENTS.// \\SOME FOLKS IN TEXAS ARE WAITING FOR FEMA RELIEF IN THE AFTERMATH OF HURRICANE DOLLY. THE STORM RIPPED AWAY ROOFS AND FLOODED HOMES BUT IT WASN'T BAD ENOUGH TO DRAW IN IMMEDIATE AID FROM THE FEDERAL GOVERNMENT. FEMA WORKERS ARE CHECKING OUT HOMES AND BUSINESSES THIS WEEK. THEY NEED TO DECIDE IF THEY'LL PAY FOR TEMPORARY HOUSING AND REPAIRS."""

response_trigger = """
TYPE: """

content = prompt + story + response_trigger

stream = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[{"role": "user", "content": content}],
    stream=True,
)
for chunk in stream:
    if chunk.choices[0].delta.content is not None:
        print(chunk.choices[0].delta.content, end="")
        
